dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - ocl-icd-opencl-dev
      - libglew-dev
      - libglfw3-dev
      - libcurl3-dev
script:
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - mkdir build && cd build
  - cmake .. && make
